/*
 * File: app/model/TomcatInstanceModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.model.TomcatInstanceModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'instanceName'
        },
        {
            type: 'string',
            name: 'ipAddr'
        },
        {
            type: 'string',
            name: 'catalinaHome'
        },
        {
            type: 'string',
            name: 'catalinaBase'
        },
        {
            type: 'int',
            name: 'sshPort'
        },
        {
            type: 'string',
            name: 'sshUsername'
        },
        {
            type: 'string',
            name: 'sshPassword'
        },
        {
            type: 'int',
            name: 'httpPort'
        },
        {
            type: 'string',
            name: 'state'
        },
        {
            type: 'int',
            name: 'applications'
        }
    ]
});