/*
 * File: app/controller/MenuController.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.controller.MenuController', {
    extend: 'Ext.app.Controller',

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        //alert(record.get("text"));
        var menuId = record.get("menuId");
        var is_leaf = record.get("leaf");
        if(menuId !== undefined){
            alert(menuId);
            if (!is_leaf){
               this.loadChildMenus(menuId);
            }

            this.showMenu(menuId);

        }

    },

    showMenu: function(menuId) {
        var activeItem = -1;

        if(menuId === "dashboard"){
            activeItem = 0;

        }else if(menuId === "tomcatInsts"){
            activeItem = 1;

        }else if(menuId === "dbcp"){
            activeItem = 2;

        }else if(menuId === "template"){
            activeItem = 3;

        }else if(menuId === "ssncluster"){
            activeItem = 4;

        }else if(menuId === "apmDash"){
            activeItem = 5;

        }else if(menuId === "apmAnaly"){
            activeItem = 6;
        }

        if(activeItem > -1){
            Ext.getCmp("centerContainer").layout.setActiveItem(activeItem);
        }
    },

    loadChildMenus: function(parentId) {
        var url = GlobalData.urlPrefix;
        var is_child_leaf = false;
        var prefix_child_menu_id = "";
        if (parentId.indexOf("tomcatMng") >=0) {
            url+="/domain/list";
            is_child_leaf = false;
            prefix_child_menu_id = "domain_tomcat_";
        }
        else if (parentId.indexOf("domain_tomcat") >= 0) {
            url+="/domain/tomcatlist";
            is_child_leaf = true;
            prefix_child_menu_id = "tomcat_";
        }
        else if (parentId.indexOf("monitoring_servers") >= 0) {
            url+="machine/list";
            is_child_leaf = true;
            prefix_child_menu_id = "monitoring_server_";
        }
        else if (parentId.indexOf("monitoring_tomcatins") >= 0) {
            url+="tomcat/list";
            is_child_leaf = true;
            prefix_child_menu_id = "monitoring_tomcat_";
        }
        else {
             return;
        }

        var treePanel = Ext.getCmp("menuTreePanel");

        //get data from ajax
        Ext.Ajax.request({
            url: url,
            success: function(resp, ops) {
                var response = Ext.decode(resp.responseText);
                for(i = 0; i < response.length; i ++){
                    treePanel.getRootNode().findChild("menuId", parentId, true).appendChild({"text":response[i].name, "menuId": prefix_child_menu_id + response[i].id, "leaf": is_child_leaf});
                }
            }
        });
    },

    loadDomainList: function(parentId) {
        alert("Domain list is loading");
    },

    loadTomcatList: function(domainId) {
        alert("Tomcat list of " + domainId + " is loading");
    },

    loadMonitoringServerList: function() {
        alert("Server list is loading");
    },

    loadMonitoringTomcatList: function() {
        alert("Monitoring tomcat list is loading");
    },

    init: function(application) {
        this.control({
            "#menuTreePanel": {
                itemclick: this.onTreepanelItemClick
            }
        });
    }

});
