/*
 * File: app/view/dashboardPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.dashboardPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dashboardpanel',

    requires: [
        'webapp.view.dashboardPanelViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    viewModel: {
        type: 'dashboardpanel'
    },
    height: 792,
    itemId: 'dashboardPanel',
    layout: 'border',

    dockedItems: [
        {
            xtype: 'container',
            dock: 'top',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Domain',
                            store: 'DomainStore'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    animCollapse: false,
                    collapseDirection: 'top',
                    collapsible: true,
                    placeholderCollapseHideMode: 2,
                    title: 'Tomcat 1',
                    titleCollapse: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            dock: 'top',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margins: '',
                                    height: 70,
                                    margin: '5 0 5 5',
                                    width: 171,
                                    title: 'Health',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margins: '',
                                    height: 70,
                                    margin: '5 0 5 5',
                                    width: 171,
                                    title: 'Today Availability',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            margin: '0 0 0 30',
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margins: '',
                                    height: 70,
                                    margin: '5 0 5 5',
                                    width: 171,
                                    title: 'Today Uptime',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '11 hrs 11 mins 26 secs'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    height: 70,
                                    margin: '5 5 5 5',
                                    width: 171,
                                    title: 'Last Downtime',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '1 hrs 51 mins 26 secs'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 5,
                            dock: 'top',
                            height: 233,
                            width: 657,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margin: '5 5 5 0',
                                    width: 600,
                                    layout: 'fit',
                                    bodyBorder: true,
                                    title: 'Server Response Time',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'cartesian',
                                            dock: 'top',
                                            height: 184,
                                            html: 'SERVER RESPONE TIME',
                                            width: 598,
                                            insetPadding: 20,
                                            axes: [
                                                {
                                                    type: 'category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Response Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: [
                                                        'y'
                                                    ],
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margin: '5 0 5 5',
                                    width: 634,
                                    title: 'Server Performance',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'cartesian',
                                            dock: 'top',
                                            height: 184,
                                            width: 598,
                                            insetPadding: 20,
                                            axes: [
                                                {
                                                    type: 'category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: [
                                                        'y'
                                                    ],
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    margin: '10 0 0 0',
                    animCollapse: false,
                    collapseDirection: 'top',
                    collapsible: true,
                    placeholderCollapseHideMode: 2,
                    title: 'Tomcat 2',
                    titleCollapse: true,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            dock: 'top',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margins: '',
                                    height: 70,
                                    margin: '5 0 5 5',
                                    width: 171,
                                    title: 'Health',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margins: '',
                                    height: 70,
                                    margin: '5 0 5 5',
                                    width: 171,
                                    title: 'Today Availability',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            margin: '0 0 0 30',
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 171,
                                            text: '100%'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    margins: '',
                                    height: 70,
                                    margin: '5 0 5 5',
                                    width: 171,
                                    title: 'Today Uptime',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '11 hrs 11 mins 26 secs'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    height: 70,
                                    margin: '5 5 5 5',
                                    width: 171,
                                    title: 'Last Downtime',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            height: 21,
                                            style: 'font-size:medium;font-weight:bold; text-align:center;',
                                            width: 37,
                                            text: '1 hrs 51 mins 26 secs'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 5,
                            dock: 'top',
                            height: 233,
                            width: 657,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margin: '5 5 5 0',
                                    width: 600,
                                    layout: 'fit',
                                    bodyBorder: true,
                                    title: 'Server Response Time',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'cartesian',
                                            dock: 'top',
                                            height: 184,
                                            html: 'SERVER RESPONE TIME',
                                            width: 598,
                                            insetPadding: 20,
                                            axes: [
                                                {
                                                    type: 'category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Response Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: [
                                                        'y'
                                                    ],
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margin: '5 0 5 5',
                                    width: 634,
                                    title: 'Server Performance',
                                    titleAlign: 'center',
                                    dockedItems: [
                                        {
                                            xtype: 'cartesian',
                                            dock: 'top',
                                            height: 184,
                                            width: 598,
                                            insetPadding: 20,
                                            axes: [
                                                {
                                                    type: 'category',
                                                    fields: [
                                                        'x'
                                                    ],
                                                    title: 'Time',
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'numeric',
                                                    fields: [
                                                        'y'
                                                    ],
                                                    title: 'ms',
                                                    position: 'bottom'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'line',
                                                    xField: 'x',
                                                    yField: [
                                                        'y'
                                                    ],
                                                    smooth: 3
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});