/*
 * File: app/view/DataSourceServerWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DataSourceServerWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.datasourceserverwindow',

    requires: [
        'webapp.view.DataSourceServerWindowViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'datasourceserverwindow'
    },
    height: 273,
    width: 517,
    title: 'Target Server',

    items: [
        {
            xtype: 'container',
            margin: '10 10 10 10',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 4,
                    title: 'Available Servers',
                    titleAlign: 'center',
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'string',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'string',
                            text: 'IP Address'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    width: 100,
                    items: [
                        {
                            xtype: 'button',
                            margin: '30 0 10 10',
                            text: '&nbsp;>&nbsp;'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 10 10',
                            text: '>>'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 10 10',
                            text: '&nbsp;<&nbsp;'
                        },
                        {
                            xtype: 'button',
                            margin: '0 0 0 10',
                            text: '<<'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 4,
                    title: 'Selected Servers',
                    titleAlign: 'center',
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'string',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'string',
                            text: 'IP Address'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            margin: '0 0 0 200',
            text: 'Save'
        },
        {
            xtype: 'button',
            margin: '0 0 0 10',
            text: 'Cancel'
        }
    ]

});