/*
 * File: app/view/DeployWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DeployWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.DeployWindow',

    requires: [
        'webapp.view.DeployWindowViewModel',
        'Ext.container.Container',
        'Ext.form.field.File',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'deploywindow'
    },
    height: 119,
    width: 400,
    layout: 'border',
    title: 'Deploy',

    dockedItems: [
        {
            xtype: 'container',
            margins: '10',
            dock: 'top',
            items: [
                {
                    xtype: 'filefield',
                    margin: 10,
                    width: 366,
                    fieldLabel: 'Label'
                },
                {
                    xtype: 'button',
                    margin: '0 0 10 100',
                    text: 'Deploy'
                },
                {
                    xtype: 'button',
                    margin: '0 0 10 10 ',
                    text: 'Cancel'
                }
            ]
        }
    ]

});