/*
 * File: app/view/DetailMonitoringMachineContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DetailMonitoringMachineContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.detailmonitoringmachinecontainer',

    requires: [
        'webapp.view.DetailMonitoringMachineContainerViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Display',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.Legend',
        'Ext.chart.series.Area',
        'Ext.chart.series.Bar',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    viewModel: {
        type: 'detailmonitoringmachinecontainer'
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'label',
                    text: 'Monitoring > Machines > 192.168.0.54'
                }
            ]
        },
        {
            xtype: 'tabpanel',
            flex: 2.5,
            id: 'tabPanel1',
            itemId: 'tabPanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: 'Overview',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'container',
                            flex: 1,
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Name',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'System health',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Hostname',
                                    value: 'Display Field'
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Host OS',
                                    value: 'Display Field'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 4,
                            dock: 'top',
                            margin: '0 0 10 0',
                            collapsible: true,
                            title: 'Utilization',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    headerPosition: 'bottom',
                                    title: 'CPU',
                                    titleAlign: 'center',
                                    items: [
                                        {
                                            xtype: 'cartesian',
                                            height: 210,
                                            width: 400,
                                            insetPadding: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    margin: '0 10 0 10',
                                    headerPosition: 'bottom',
                                    title: 'Memory',
                                    titleAlign: 'center',
                                    items: [
                                        {
                                            xtype: 'cartesian',
                                            height: 210,
                                            width: 400,
                                            insetPadding: 35
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    headerPosition: 'bottom',
                                    title: 'Disk',
                                    titleAlign: 'center',
                                    items: [
                                        {
                                            xtype: 'cartesian',
                                            height: 210,
                                            width: 400,
                                            insetPadding: 35
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 3,
                            dock: 'top',
                            collapsible: true,
                            title: 'System load',
                            dockedItems: [
                                {
                                    xtype: 'cartesian',
                                    dock: 'top',
                                    height: 250,
                                    width: 400,
                                    insetPadding: 20,
                                    axes: [
                                        {
                                            type: 'category',
                                            fields: [
                                                'x'
                                            ],
                                            title: 'Category Axis',
                                            position: 'bottom'
                                        },
                                        {
                                            type: 'numeric',
                                            fields: [
                                                'y'
                                            ],
                                            title: 'Numeric Axis',
                                            position: 'bottom'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            xField: 'x',
                                            yField: [
                                                'y'
                                            ],
                                            smooth: 3
                                        },
                                        {
                                            type: 'line',
                                            xField: 'x',
                                            yField: [
                                                'y'
                                            ],
                                            smooth: 3
                                        },
                                        {
                                            type: 'line',
                                            xField: 'x',
                                            yField: [
                                                'y'
                                            ],
                                            smooth: 3
                                        }
                                    ],
                                    legend: {
                                        xtype: 'legend'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: 'CPU',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            dock: 'top',
                            margin: '0 0 10 0',
                            title: 'CPU utilization',
                            dockedItems: [
                                {
                                    xtype: 'cartesian',
                                    dock: 'top',
                                    height: 250,
                                    width: 400,
                                    insetPadding: 20,
                                    axes: [
                                        {
                                            type: 'category',
                                            fields: [
                                                'x'
                                            ],
                                            title: 'Category Axis',
                                            position: 'bottom'
                                        },
                                        {
                                            type: 'numeric',
                                            fields: [
                                                'y'
                                            ],
                                            title: 'Numeric Axis',
                                            position: 'bottom'
                                        }
                                    ],
                                    series: [
                                        {
                                            type: 'line',
                                            xField: 'x',
                                            yField: [
                                                'y'
                                            ],
                                            smooth: 3
                                        },
                                        {
                                            type: 'area'
                                        },
                                        {
                                            type: 'area'
                                        },
                                        {
                                            type: 'area'
                                        },
                                        {
                                            type: 'area'
                                        }
                                    ],
                                    legend: {
                                        xtype: 'legend'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            dock: 'top',
                            title: 'CPU Utilization by cores',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    dock: 'top',
                                    height: 190,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'cartesian',
                                                    height: 250,
                                                    width: 400,
                                                    insetPadding: 20,
                                                    axes: [
                                                        {
                                                            type: 'category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'bottom'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: [
                                                                'y'
                                                            ],
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'cartesian',
                                                    height: 250,
                                                    width: 400,
                                                    insetPadding: 20,
                                                    axes: [
                                                        {
                                                            type: 'category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'bottom'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: [
                                                                'y'
                                                            ],
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    dock: 'top',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'cartesian',
                                                    height: 250,
                                                    width: 400,
                                                    insetPadding: 20,
                                                    axes: [
                                                        {
                                                            type: 'category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'bottom'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: [
                                                                'y'
                                                            ],
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: 'fit',
                                            items: [
                                                {
                                                    xtype: 'cartesian',
                                                    height: 250,
                                                    width: 400,
                                                    insetPadding: 20,
                                                    axes: [
                                                        {
                                                            type: 'category',
                                                            fields: [
                                                                'x'
                                                            ],
                                                            title: 'Category Axis',
                                                            position: 'bottom'
                                                        },
                                                        {
                                                            type: 'numeric',
                                                            fields: [
                                                                'y'
                                                            ],
                                                            title: 'Numeric Axis',
                                                            position: 'bottom'
                                                        }
                                                    ],
                                                    series: [
                                                        {
                                                            type: 'line',
                                                            xField: 'x',
                                                            yField: [
                                                                'y'
                                                            ],
                                                            smooth: 3
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: 'Disk',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    dockedItems: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            dock: 'top',
                            title: 'Disk Utilization'
                        }
                    ],
                    items: [
                        {
                            xtype: 'cartesian',
                            height: 250,
                            width: 400,
                            insetPadding: 20,
                            axes: [
                                {
                                    type: 'category',
                                    fields: [
                                        'x'
                                    ],
                                    position: 'left',
                                    title: 'Category Axis'
                                },
                                {
                                    type: 'numeric',
                                    fields: [
                                        'y1',
                                        'y2',
                                        'y3'
                                    ],
                                    title: 'Numeric Axis',
                                    position: 'bottom'
                                }
                            ],
                            series: [
                                {
                                    type: 'bar',
                                    xField: 'x',
                                    yField: [
                                        'y1',
                                        'y2',
                                        'y3'
                                    ]
                                }
                            ],
                            legend: {
                                xtype: 'legend'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: 'Network',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: 'Network interfaces',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Health'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Status'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Speed (Mbps)'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Input traffic(Kbps)'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Output Traffic(Kbps)'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Errors'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    autoScroll: true,
                    title: 'Hardware health',
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'top',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: 'Fan',
                                    titleAlign: 'center',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Sensor'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Health'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    margin: '0 10 0 10',
                                    title: 'Power',
                                    titleAlign: 'center',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Sensor'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Health'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: 'Temperature',
                                    titleAlign: 'center',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Sensor'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Health'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'toolbar'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            dock: 'top',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: 'Fan',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Sensor'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Health'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: 'Power',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Sensor'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Health'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});