/*
 * File: app/view/DomainContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.DomainContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.domaincontainer',

    requires: [
        'webapp.view.DomainContainerViewModel',
        'Ext.form.Label',
        'Ext.form.field.Display',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.toolbar.Separator',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'domaincontainer'
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 0.5,
            height: 47,
            items: [
                {
                    xtype: 'label',
                    text: 'Tomcat Management > Domain 1'
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1.5,
            height: 150,
            layout: 'column',
            title: 'Overview',
            items: [
                {
                    xtype: 'displayfield',
                    width: 164,
                    fieldLabel: 'Name:',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    width: 381,
                    fieldLabel: 'Tomcat instances:',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    width: 249,
                    fieldLabel: 'Type',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    style: '{text-align:right;font-weight:bold;}',
                    fieldLabel: 'Data grid server group:'
                }
            ]
        },
        {
            xtype: 'tabpanel',
            flex: 8,
            id: 'tomcatInstTabPanel1',
            itemId: 'tomcatInstTabPanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    title: 'Tomcat instances',
                    dockedItems: [
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            height: 326,
                            title: '',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'No.'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Host name'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'IP Address'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Status'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'pagingtoolbar',
                                    dock: 'bottom',
                                    width: 360,
                                    displayInfo: true
                                },
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'mybutton',
                                            text: 'New'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Filtering'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Version'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Applications',
                    dockedItems: [
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            title: '',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Path'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Version'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Display name'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Sessions'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Status'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Tomcat instance'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Session Timeout'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'mybutton1',
                                            text: 'Deploy'
                                        },
                                        {
                                            xtype: 'tbseparator'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Filtering'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'top',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Sessions',
                    dockedItems: [
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            title: '',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Key'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Value'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Location'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Filtering'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'top',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: 'Clustering configuration',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'New'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Filtering'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Version'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Set active'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Delete'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            height: 42,
                            items: [
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Compare to'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Compare'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            dock: 'top',
                            title: '',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Value'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'Action'
                                }
                            ]
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'top',
                            width: 360,
                            displayInfo: true
                        }
                    ]
                }
            ]
        }
    ]

});