/*
 * File: app/view/LinkNewDataSourceWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.LinkNewDataSourceWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.LinkNewDataSourceWindow',

    requires: [
        'webapp.view.LinkNewDataSourceWindowViewModel',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'linknewdatasourcewindow'
    },
    height: 288,
    width: 574,
    title: 'Link to new Datasource',

    dockedItems: [
        {
            xtype: 'container',
            dock: 'top',
            margin: '10 0 0 10',
            items: [
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Tomcat instance',
                    value: 'Display Field'
                },
                {
                    xtype: 'displayfield',
                    fieldLabel: 'Status:',
                    value: 'Display Field'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            title: '',
            forceFit: true,
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Select'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Data source Name'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'JDBC URL'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Server No'
                }
            ]
        },
        {
            xtype: 'checkboxfield',
            fieldLabel: '',
            boxLabel: 'Restart tomcat instance after linking new datasource.'
        },
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'button',
                    margin: '0 0 0 180',
                    text: 'OK'
                },
                {
                    xtype: 'button',
                    margin: '0 0 0 10',
                    text: 'Cancel'
                }
            ]
        }
    ]

});