/*
 * File: app/view/TomcatInstanceWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.TomcatInstanceWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.TomcatInstanceWindow',

    requires: [
        'webapp.view.TomcatInstanceWindowViewModel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'tomcatinstancewindow'
    },
    height: 532,
    width: 449,
    title: 'New Tomcat Instance',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            height: 336,
            items: [
                {
                    xtype: 'container',
                    margin: '10 10 10 10',
                    items: [
                        {
                            xtype: 'combobox',
                            width: 399,
                            fieldLabel: 'Domain',
                            store: 'DomainStore'
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Domain type:',
                            value: 'Display Field'
                        },
                        {
                            xtype: 'textfield',
                            width: 400,
                            fieldLabel: 'Instance name'
                        },
                        {
                            xtype: 'combobox',
                            width: 399,
                            fieldLabel: 'Server',
                            store: 'ServerStore'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '10 10 10 10',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 7,
                            autoScroll: true,
                            manageHeight: false,
                            title: 'Data source',
                            forceFit: true,
                            store: 'DatasourceStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Select'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'JDBC Url'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    dataIndex: 'bool',
                                    text: 'Servers'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxfield',
                            flex: 0.5,
                            fieldLabel: '',
                            boxLabel: 'Automatically start tomcat after being created'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    margin: '20 0 0 150',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    margin: '20 0 0 10',
                    text: 'Cancel'
                }
            ]
        }
    ]

});