/*
 * File: app/view/TomcatInstanceContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.TomcatInstanceContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.tomcatinstancecontainer',

    requires: [
        'webapp.view.TomcatInstanceContainerViewModel',
        'Ext.form.Label',
        'Ext.form.field.Display',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'tomcatinstancecontainer'
    },

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 0.5,
            height: 47,
            items: [
                {
                    xtype: 'label',
                    text: 'Tomcat Management > Domain 1> Tomcat 1'
                }
            ]
        },
        {
            xtype: 'panel',
            flex: 1.5,
            height: 389,
            manageHeight: false,
            title: 'Overview',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 164,
                    fieldLabel: 'Host name:',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 249,
                    fieldLabel: 'Status',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 249,
                    fieldLabel: 'IP Address',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 249,
                    fieldLabel: 'Ports:',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 164,
                    fieldLabel: 'Web server',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 164,
                    fieldLabel: 'JVM Version',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 164,
                    fieldLabel: 'OS Name',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    flex: 1.5,
                    width: 164,
                    fieldLabel: 'Domain',
                    value: ''
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            text: 'Start'
                        },
                        {
                            xtype: 'button',
                            text: 'Stop'
                        },
                        {
                            xtype: 'button',
                            text: 'Restart'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            flex: 8,
            title: 'Data sources',
            forceFit: true,
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Name'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'JDBC URL'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Servers'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Min Connection Pool'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Max Connection Pool'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Timeout'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'mybutton10',
                            text: 'Link new Data source'
                        }
                    ]
                }
            ]
        }
    ]

});