/*
 * File: app/view/UserMntContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('webapp.view.UserMntContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.usermntcontainer',

    height: 441,
    width: 683,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'datefield',
                    fieldLabel: 'Date'
                },
                {
                    xtype: 'gridpanel',
                    height: 334,
                    autoScroll: true,
                    title: 'User List',
                    emptyText: 'No data available.',
                    scroll: 'horizontal',
                    store: 'UserStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'username',
                            text: 'User name'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'email',
                            text: 'Email'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'full_name',
                            text: 'Full name'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'last_login_date',
                            text: 'Last login date'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'created_date',
                            text: 'Created date'
                        },
                        {
                            xtype: 'actioncolumn',
                            dataIndex: 'id',
                            items: [
                                {

                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'New'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Filtering',
                                    emptyText: 'Username'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});